language: csharp
dist: trusty
dotnet: 1.0.1
mono: none
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
script:
  - ./bin/fetch-configlet
  - ./bin/configlet lint .
  - ./build.sh
cache:
  directories:
  - $HOME/.nuget/packages
